[pytest]
testpaths = tests
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
branch = true
source = app

[coverage:report]
exclude_also =
    def __repr__
    raise NotImplementedError
    if __name__ == .__main__.:
show_missing = true
skip_covered = false

[coverage:html]
directory = htmlcov
