QUOTES = [
    "Stop waiting for motivation. Build systems that expose your excuses.",
    "Accountability is the mirror most people avoid because it tells the truth.",
    "Callous your mind by doing the work you keep negotiating with.",
    "You do not need a better mood. You need better standards.",
    "The truth is simple: you keep quitting when it gets inconvenient.",
    "Discipline is choosing the hard thing before life chooses it for you.",
    "If you need hype to start, you are still owned by comfort.",
    "Your feelings are not a project manager. Finish the task anyway.",
    "Every excuse you protect becomes a ceiling you live under.",
    "The weak look for inspiration. The strong audit their habits.",
    "You are not overworked. You are under-disciplined in the moments that matter.",
    "Confidence comes from receipts, not affirmations.",
    "The calloused mind is built in the reps nobody claps for.",
    "Most people want relief. Very few want responsibility.",
    "Get honest about your habits and the story changes fast.",
    "You keep saying later because later lets you avoid judgment now.",
    "Being soft is expensive. You pay for it in every missed standard.",
    "Real growth starts when you stop asking your mood for permission.",
    "Comfort is a slow addiction that makes average feel normal.",
    "When you face the truth daily, excuses lose oxygen.",
    "ADHD is not your permission slip to drift. Build the rails and use them.",
    "A distracted hour is still your hour. Own it and reset faster.",
    "Your brain likes novelty. Your life gets built by repetition.",
    "Stop romanticizing the perfect setup. Start ugly and keep moving.",
    "You do not need five tabs open. You need one target and ten hard minutes.",
    "When attention slips, recover quicker. That is the rep that counts.",
    "The planner is not the work. The checklist is not the work. Do the work.",
    "If your system breaks on a bad day, it was never a system. Fix it.",
    "Impulse is loud. Standards need to be louder.",
    "You are not behind because of one bad day. You are behind when you stop restarting.",
]
